services:
  oracle:
    image: gvenzl/oracle-free:latest
    container_name: oracle_newsletter
    volumes:
      - oracle_data:/opt/oracle/oradata
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      APP_USER: ${APP_USER}
      APP_USER_PASSWORD: ${APP_USER_PASSWORD}
volumes:
  oracle_data: