services:
  oracle:
    image: gvenzl/oracle-free:latest
    container_name: oracle_newsletter
    volumes:
      - oracle_data:/opt/oracle/oradata
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      ORACLE_APP_USER: ${DB_USERNAME}
      ORACLE_APP_USER_PASSWORD: ${DB_PASSWORD}
volumes:
  oracle_data: