spring.application.name=newsletter

# Banco de Dados via Variáveis de Ambiente
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# JoinFaces / JSF Config
joinfaces.jsf.default-suffix=.xhtml
joinfaces.faces.project-stage=Development