CREATE TABLE newsletter_customer (
    ID NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    MAIL VARCHAR2(150) NOT NULL UNIQUE,
    REGISTER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);