CREATE TABLE newsletter_customer (
    ID NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) NOT NULL UNIQUE,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);