CREATE OR REPLACE TRIGGER TRG_BEFORE_INSERT_CLIENTE
    BEFORE INSERT ON newsletter_customer
    FOR EACH ROW
BEGIN
:NEW.MAIL := LOWER(TRIM(:NEW.MAIL));
END;
/

CREATE OR REPLACE PROCEDURE PRC_REGISTER_CLIENT (
    P_NAME IN VARCHAR2,
    P_MAIL IN VARCHAR2,
    P_ID   OUT NUMBER
) AS
BEGIN
INSERT INTO newsletter_customer (NAME, MAIL)
VALUES (P_NAME, P_MAIL)
RETURNING ID INTO P_ID;

COMMIT;
END PRC_REGISTER_CLIENT;
/